In [30]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [10]:
syn = pd.read_csv('./synsig_data.csv')

In [6]:
s2 = pd.read_csv('./table_s2.csv')

In [14]:
s3 = pd.read_csv('./table_s3.csv')

In [15]:
s4 = pd.read_csv('./table_s4.csv')
s5 = pd.read_csv('./table_s5.csv')

In [12]:
s23 = s2.merge(s3, how='outer', on='Gene Symbol', suffixes=['_s2', '_s3'] )

In [16]:
s234 = s23.merge(s4, how='outer', on='Gene Symbol')

In [18]:
s45 = s4.merge(s5, how='outer', on='Gene Symbol', suffixes=['_s4', '_s5'])

In [19]:
s2345 = s23.merge(s45, how='outer', on='Gene Symbol')

In [20]:
s2345

,Gene Symbol,Sum_Coverage_s2,Sum_Num Proteins_s2,Sum_Num Unique Peptides_s2,Sum_Num Peptides_s2,Sum_Num PSMs_s2,Score A2_s2,Coverage A2_s2,Num Peptides A2_s2,Num PSM A2_s2,...,WT2_s4,WT3_s4,CountOfPeptide1_s5,FirstOfClean_Peptide_s5,Spectral count_s5,MSGF_SpecProb_s5,Protein_ID_s5,WT1_s5,WT2_s5,WT3_s5
0,AAK1,11.13,3.0,6.0,6.0,10.0,92.75,9.89,5.0,5.0,...,23.006548,23.032034,6.0,AGQTQPNPGILPIQPALTPR,8.0,3.912960e-30,AAK1_MOUSE,18.037680,17.895012,17.839016
1,ABCC12,10.38,7.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABCF1,3.02,3.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,...,17.536928,17.152325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABI1,10.31,16.0,2.0,4.0,8.0,44.63,10.31,4.0,4.0,...,19.913868,20.466902,5.0,AKHGNNQPAR,6.0,2.471550e-22,ABI1_MOUSE,19.451442,19.523618,19.539083
4,ABI2,18.74,17.0,5.0,7.0,17.0,70.92,18.74,7.0,8.0,...,25.233752,25.369580,5.0,ALFDSYTNLER,6.0,5.559050e-22,ABI2_MOUSE,19.673747,19.837874,19.800385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6869,TTC9B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,2.0,AAQGARPGGLPTPSPGPTTSPGPAR,2.0,3.675600e-20,TTC9B_MOUSE,13.218838,13.194072,13.055154
6870,TY3H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,AVSEQDTKQAEAVTSPR,1.0,9.312290e-19,TY3H_MOUSE,14.852852,14.814334,15.179194
6871,UBL4A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,HFSVADASR,1.0,2.657750e-11,UBL4A_MOUSE,14.740849,13.166293,15.949496
6872,ZFY27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,SCSNCGNSFCSR,1.0,1.062580e-17,ZFY27_MOUSE,12.213751,12.411871,12.003090
6873,ZRAB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,RSECNM*CNTPK,1.0,7.077280e-12,ZRAB2_MOUSE,11.988230,11.972232,11.261627

In [22]:
syns2345 = syn.merge(s2345, how='left', left_on='genes', right_on='Gene Symbol')

In [24]:
syn

,genes,avg_scores,syngo,syndb,synsysnet,cortex,striatum,fetal,ngn2,Lit Sum,...,Membrane_Cell Adhesion,Other Regulators,Scaffolds_Adaptors,Cytoskeletal,Calcium Ion Binding,Other Enzymes,Other protein binders,unknown functions,Function Total,MF Terms
0,APP,5.848907,1,0,1,1,1,1,1,2,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,['serine-type endopeptidase inhibitor activity...
1,HSP90AB1,5.619269,0,1,0,1,1,1,1,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"['protein kinase regulator activity', 'dATP bi..."
2,HSPA8,5.474445,1,1,1,1,1,1,1,3,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"['ubiquitin protein ligase binding', 'clathrin..."
3,EGFR,5.469596,0,0,0,1,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,"['protein phosphatase binding', 'ATPase bindin..."
4,TP53,5.461622,0,0,0,0,0,0,0,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,"['protease binding', 'MDM2/MDM4 family protein..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11077,MND1,NaN,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['double-stranded DNA binding']
11078,PSMC5,NaN,0,0,0,1,0,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['thyrotropin-releasing hormone receptor bindi...
11079,PLEC,NaN,0,1,0,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['cadherin binding', 'structural constituent o..."
11080,PLCE1,NaN,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['guanyl-nucleotide exchange factor activity',..."
11081,F2RL1,NaN,0,1,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['signaling receptor binding', 'thrombin-activ..."

In [23]:
syns2345

,genes,avg_scores,syngo,syndb,synsysnet,cortex,striatum,fetal,ngn2,Lit Sum,...,WT2_s4,WT3_s4,CountOfPeptide1_s5,FirstOfClean_Peptide_s5,Spectral count_s5,MSGF_SpecProb_s5,Protein_ID_s5,WT1_s5,WT2_s5,WT3_s5
0,APP,5.848907,1,0,1,1,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,APP,5.848907,1,0,1,1,1,1,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,HSP90AB1,5.619269,0,1,0,1,1,1,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,HSPA8,5.474445,1,1,1,1,1,1,1,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,EGFR,5.469596,0,0,0,1,0,0,0,0,...,17.002954,16.932112,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,MND1,NaN,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11158,PSMC5,NaN,0,0,0,1,0,1,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11159,PLEC,NaN,0,1,0,1,1,1,1,1,...,26.131442,25.790356,27.0,AQLEPVASPAKKPK,28.0,7.882280e-19,PLEC_MOUSE,19.954686,19.927921,19.862542
11160,PLCE1,NaN,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11161,F2RL1,NaN,0,1,0,0,0,0,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
s2345.loc[s2345['Gene Symbol'] == 'APP']

,Gene Symbol,Sum_Coverage_s2,Sum_Num Proteins_s2,Sum_Num Unique Peptides_s2,Sum_Num Peptides_s2,Sum_Num PSMs_s2,Score A2_s2,Coverage A2_s2,Num Peptides A2_s2,Num PSM A2_s2,Score A4_s2,Coverage A4_s2,Num Peptides A4_s2,Num PSM A4_s2,Num AAs_s2,MW kDa_s2,calc pI_s2,Sum_Coverage_s3,Sum_Num Proteins_s3,Sum_Num Unique Peptides_s3,Sum_Num Peptides_s3,Sum_Num PSMs_s3,Score A2_s3,Coverage A2_s3,Num Peptides A2_s3,Num PSM A2_s3,Score A4_s3,Coverage A4_s3,Num Peptides A4_s3,Num PSM A4_s3,Num AAs_s3,MW kDa_s3,calc pI_s3,CountOfPeptide1_s4,FirstOfClean_Peptide_s4,Spectral count_s4,MSGF_SpecProb_s4,Protein_ID_s4,WT1_s4,WT2_s4,WT3_s4,CountOfPeptide1_s5,FirstOfClean_Peptide_s5,Spectral count_s5,MSGF_SpecProb_s5,Protein_ID_s5,WT1_s5,WT2_s5,WT3_s5
85,APP,5.77,14.0,1.0,2.0,6.0,73.66,5.77,2.0,3.0,0.0,5.77,2.0,3.0,485.0,55.1,4.82,14.55,15.0,6.0,6.0,19.0,143.91,14.55,6.0,9.0,27.76,14.55,6.0,10.0,639.0,72.5,4.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,APP,18.93,1.0,1.0,2.0,5.0,63.60,18.93,2.0,3.0,0.0,6.43,1.0,2.0,280.0,31.9,5.54,14.55,15.0,6.0,6.0,19.0,143.91,14.55,6.0,9.0,27.76,14.55,6.0,10.0,639.0,72.5,4.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
s2.loc[s2['Gene Symbol'] == 'APP']

,Gene Symbol,Sum_Coverage,Sum_Num Proteins,Sum_Num Unique Peptides,Sum_Num Peptides,Sum_Num PSMs,Score A2,Coverage A2,Num Peptides A2,Num PSM A2,Score A4,Coverage A4,Num Peptides A4,Num PSM A4,Num AAs,MW kDa,calc pI
80,APP,5.77,14,1,2,6,73.66,5.77,2.0,3.0,0.0,5.77,2.0,3.0,485,55.1,4.82
81,APP,18.93,1,1,2,5,63.60,18.93,2.0,3.0,0.0,6.43,1.0,2.0,280,31.9,5.54

In [34]:
train = syn[['genes', 'training']]

In [36]:
train = train.loc[train['training'] != 'no']

In [37]:
train

       genes training
10108  LAMC1      pos
10109    TNR      pos
10110  MYO5A      pos
10111   ANO1      pos
10112    FGA      pos
...      ...      ...
11077   MND1      neg
11078  PSMC5      neg
11079   PLEC      neg
11080  PLCE1      neg
11081  F2RL1      neg

[974 rows x 2 columns]

In [38]:
train.to_csv('./training.csv', index=False)

In [40]:
pred = syn[['genes', 'training', 'Synapse Percentile']]
pred = pred.loc[pred['training'] == 'no']

In [43]:
pred = pred.drop('training', axis=1)

In [45]:
pred.to_csv('./predicted.csv', index=False)

In [46]:
train = pd.read_csv('./training.csv')

In [48]:
train = train.sort_values('genes')

In [50]:
train.to_csv('./training.csv', index=False)

In [51]:
pred = pd.read_csv('./predicted.csv')
pred = pred.sort_values('genes')
pred.to_csv('./predicted.csv', index=False)

In [52]:
pd.read_csv('./table_s2.csv')

,Gene Symbol,Sum_Coverage,Sum_Num Proteins,Sum_Num Unique Peptides,Sum_Num Peptides,Sum_Num PSMs,Score A2,Coverage A2,Num Peptides A2,Num PSM A2,Score A4,Coverage A4,Num Peptides A4,Num PSM A4,Num AAs,MW kDa,calc pI
0,AAK1,11.13,3,6,6,10,92.75,9.89,5.0,5.0,5.18,8.12,5.0,5.0,961,103.8,6.60
1,ABCC12,10.38,7,1,1,1,NaN,NaN,NaN,NaN,0.00,10.38,1.0,1.0,106,12.0,8.82
2,ABCF1,3.02,3,1,1,1,NaN,NaN,NaN,NaN,0.00,3.02,1.0,1.0,596,67.6,8.19
3,ABI1,10.31,16,2,4,8,44.63,10.31,4.0,4.0,3.93,10.31,4.0,4.0,388,42.6,6.04
4,ABI2,18.74,17,5,7,17,70.92,18.74,7.0,8.0,11.51,18.74,7.0,9.0,475,52.4,6.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1472,NaN,13.98,1,1,8,440,4569.62,13.98,8.0,217.0,497.56,13.98,8.0,223.0,372,41.7,4.87
1473,NaN,10.43,4,1,1,3,21.73,10.43,1.0,2.0,0.00,10.43,1.0,1.0,163,17.6,7.43
1474,NaN,4.28,2,2,2,3,27.42,1.86,1.0,1.0,0.00,4.28,2.0,2.0,538,61.2,7.31
1475,NaN,3.06,1,1,1,2,0.00,3.06,1.0,1.0,0.00,3.06,1.0,1.0,196,21.1,11.12
1476,NaN,7.38,2,1,1,1,NaN,NaN,NaN,NaN,0.00,7.38,1.0,1.0,149,16.1,8.32