In [2]:
import pandas as pd

In [5]:
#Table 2
t2a = pd.read_csv('../originalData/Table S2.csv', header=2)

#Remove NaN rows
t2b = t2a.dropna(how='all')

#Remove NaN columns
t2c = t2b.dropna(axis=1, how='all')

#Change headers
header = [
    'Gene Symbol',
    'Accession',
    'Description',
    'SumCoverage',
    'SumNum Proteins',
    'SumNum Unique Peptides',
    'SumNum Peptides',
    'SumNum PSMs',
    'Score A2',
    'Coverage A2',
    'Num Peptides A2',
    'Num PSM A2',
    'Score A4',
    'Coverage A4',
    'Num Peptides A4',
    'Num PSM A4',
    'Num AAs',
    'MW kDa',
    'calc pI'
]
t2c.columns = header

#Sort
t2d = t2c.sort_values('Gene Symbol')

#Remove rows where gene symbol is NaN
t2e = t2d[t2d['Gene Symbol'].notna()]

#Remove unused columns
t2f = t2e.drop(['Accession', 'Description'], axis=1)

#Write to file
t2f.to_csv('../data/table_s2.csv', index=False)

In [23]:
#Table 3
t3a = pd.read_csv('./originalData/Table S3.csv', header=2)

#Remove NaN rows
#t3b = t3a.dropna(how='all')

#Remove NaN columns
#t3c = t3b.dropna(axis=1, how='all')

#Change headers
header = [
    'Gene Symbol',
    'Accession',
    'Description',
    'SumCoverage',
    'SumNum Proteins',
    'SumNum Unique Peptides',
    'SumNum Peptides',
    'SumNum PSMs',
    'Score A2',
    'Coverage A2',
    'Num Peptides A2',
    'Num PSM A2',
    'Score A4',
    'Coverage A4',
    'Num Peptides A4',
    'Num PSM A4',
    'Num AAs',
    'MW kDa',
    'calc pI', '','','','','','','',''
]
t3a.columns = header

#Sort
t3d = t3a.sort_values('Gene Symbol')

#Remove rows where gene symbol is NaN
t3e = t3d[t3d['Gene Symbol'].notna()]

#Remove unused columns
t3f = t3e.drop(['Accession', 'Description'], axis=1)

#Write to file
t3a.to_csv('./table_s3.csv', index=False)

In [24]:
t3f

,Gene Symbol,SumCoverage,SumNum Proteins,SumNum Unique Peptides,SumNum Peptides,SumNum PSMs,Score A2,Coverage A2,Num Peptides A2,Num PSM A2,...,MW kDa,calc pI,,,,,,,,
3304,AACS,6.99,4.0,1.0,1.0,1.0,27.05,6.99,1.0,1.0,...,16.6,5.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2603,AAGAB,4.44,1.0,1.0,1.0,4.0,47.67,4.44,1.0,2.0,...,34.6,4.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
581,AAK1,27.78,3.0,16.0,16.0,52.0,843.08,27.78,16.0,26.0,...,103.8,6.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
270,AARS,26.03,2.0,22.0,22.0,103.0,1242.73,22.00,19.0,50.0,...,106.7,5.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1954,AARS2,4.37,1.0,4.0,4.0,9.0,32.65,4.37,4.0,5.0,...,107.3,6.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,ZW10,5.01,2.0,3.0,3.0,5.0,25.33,3.47,2.0,2.0,...,88.8,6.27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3113,ZYG11B,1.94,3.0,1.0,1.0,2.0,30.36,1.94,1.0,1.0,...,63.5,6.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1623,ZYX,10.12,6.0,3.0,3.0,13.0,156.68,10.12,3.0,7.0,...,45.0,8.22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1377,ZZEF1,3.68,4.0,7.0,7.0,18.0,252.34,3.68,7.0,9.0,...,330.9,5.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
956,hCG_2044799,14.75,2.0,9.0,9.0,30.0,267.66,10.59,8.0,13.0,...,84.6,4.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN